[ src ]

url = "https://ftp.gnu.org/gnu/<prog>/<prog>-<ver>.tar.xz"
src_type = "tar"
src_dirname = "<prog>-<ver>"



[ std ]

env = [ "FORCE_UNSAFE_CONFIGURE=1" ]
prepare = "tar --no-same-owner -xf <src_path> -C <tmp_dir>"
configure = "./configure
	--prefix=/usr
	--without-xattrs
	--disable-acl
	--disable-nls
	--disable-dependency-tracking"

build = "make"
pkg_create = "make DESTDIR=<pkg_dir> install &&
	rm -r <pkg_dir>/usr/share/info/"



[ init_cross ]

env = []
prepare = "tar --no-same-owner -xf <src_path> -C <tmp_dir>"
configure = "./configure
	--prefix=/usr
	--host=${TARGET_TRI}
	--build=$(build-aux/config.guess)
	--without-xattrs
	--disable-acl
	--disable-nls
	--disable-dependency-tracking"

build = "make"
pkg_create = "make DESTDIR=<pkg_dir> install"



[ init ]

env = [ "FORCE_UNSAFE_CONFIGURE=1" ]
prepare = "tar --no-same-owner -xf <src_path> -C <tmp_dir>"
configure = "./configure
	--prefix=/usr
	--without-xattrs
	--disable-acl
	--disable-nls
	--disable-dependency-tracking"

build = "make"
pkg_create = "make DESTDIR=<pkg_dir> install"
