[ src ]

url = ""
src_type = "files"
src_dirname = ""



[ std ]

env = []
prepare = ""
configure = ""
build = ""
pkg_create = ""



[ bootstrap ]

env = []
prepare = ""
configure = ""
build = ""
pkg_create = ""

