[ src ]

url = https://ftp.gnu.org/gnu/<prog>/<prog>-<ver>.tar.xz
src_type = tar
src_dirname = <prog>-<ver>



[ vars ]

var def_config = --disable-static
	--disable-dependency-tracking



[ std ]

env =
prepare = tar --no-same-owner -xf <src_path> -C <tmp_dir>
configure = ./configure
	--prefix=/usr
	--sysconfdir=/etc
	--mandir=/usr/share/man
	<def_config>

build = make
pkg_create = make DESTDIR=<pkg_dir> install
