[ src ]

url = "https://www.lua.org/ftp/lua-<ver>.tar.gz"
src_type = "tar"
src_dirname = "lua-<ver>"



[ std ]

env = []
prepare = "tar --no-same-owner -xf <src_path> -C <tmp_dir>"
configure = "patch -Np1 -i <prog_dir>/patch/liblua.so.patch &&
	sed -i '/#define LUA_ROOT/s:/usr/local/:/usr/:' src/luaconf.h &&
	sed -r -e '/^LUA_(SO|A|T)=/ s/lua/lua<ver_short>/'
		-e '/^LUAC_T=/ s/luac/luac<ver_short>/'
		-i src/Makefile"

build = "make MYCFLAGS=\"${CFLAGS} -fPIC\" MYLDFLAGS=\"${LDFLAGS}\" linux"
pkg_create = "make TO_BIN='lua<ver_short> luac<ver_short>'                     \
	TO_LIB='liblua<ver_short>.so liblua<ver_short>.so.<ver_short>
		liblua<ver_short>.so.<ver>'
	INSTALL_DATA='cp -d'
	INSTALL_TOP=${PWD}/install/usr
	INSTALL_INC=${PWD}/install/usr/include/lua<ver_short>
	INSTALL_MAN=${PWD}/install/usr/share/man/man1
	install &&
	mv install/usr/share/man/man1/{lua.1,lua<ver_short>} &&
	mv install/usr/share/man/man1/{luac.1,luac<ver_short>} &&
	ln -s liblua<ver_short>.so install/usr/lib/liblua.so.<ver_short> &&
	ln -s liblua<ver_short>.so install/usr/lib/liblua.so.<ver> &&
	cp -a install/* <pkg_dir>/ &&
	install -Dm644 <prog_dir>/files/lua.pc
		<pkg_dir>/usr/lib/pkgconfig/<prog>.pc &&
	sed -i 's|__VER__|<ver_short>|g'
		<pkg_dir>/usr/lib/pkgconfig/<prog>.pc &&
	sed -i 's|__REL__|<ver>|g' <pkg_dir>/usr/lib/pkgconfig/<prog>.pc &&
	ln -sf <prog>.pc <pkg_dir>/usr/lib/pkgconfig/lua<ver_short>.pc &&
	ln -sf <prog>.pc <pkg_dir>/usr/lib/pkgconfig/lua-<ver_short>.pc"
