[ src ]

url = "https://www.stunnel.org/downloads/archive/<ver_short>.x/stunnel-<ver>.tar.gz"
src_type = "tar"
src_dirname = "<prog>-<ver>"



[ std ]

env = []
prepare = "tar --no-same-owner -xf <src_path> -C <tmp_dir>"
configure = "./configure
	--prefix=/usr
	--sysconfdir=/etc
	--localstatedir=/var
	--disable-libwrap
	--disable-nls
	--disable-dependency-tracking"

build = "make"
pkg_create = "make DESTDIR=<pkg_dir> install &&
	mv <pkg_dir>/etc/ <pkg_dir>/usr/share/ &&
	rm <pkg_dir>/usr/share/doc/stunnel/*.*"
