[ src ]

url = https://www.alsa-project.org/files/pub/utils/<prog>-<ver>.tar.bz2
src_type = tar
src_dirname = <prog>-<ver>



[ vars ]



[ std ]

env =
prepare = tar --no-same-owner -xf <src_path> -C <tmp_dir>
configure = ./configure
	--prefix=/usr
	--sbindir=/usr/bin
	--enable-alsatopology
	--disable-static
	--disable-nls
	--disable-dependency-tracking

build = make
pkg_create = make DESTDIR=<pkg_dir> install &&
	rm -r <pkg_dir>/usr/share/man/fr/
