[ src ]

url = "https://zlib.net/zlib-<ver>.tar.gz"
src_type = "tar"
src_dirname = "<prog>-<ver>"



[ std ]

env = []
prepare = "tar --no-same-owner -xf <src_path> -C <tmp_dir>"
configure = "./configure --prefix=/usr"
build = "make"
pkg_create = "make DESTDIR=<pkg_dir> install && rm <pkg_dir>/usr/lib/libz.a"



[ musl ]

env = [ "CC=musl-gcc -static" ]
prepare = "tar --no-same-owner -xf <src_path> -C <tmp_dir>"
configure = "./configure --prefix=/musl --libdir=/lib --static"
build = "make"
pkg_create = "make DESTDIR=<pkg_dir> install"



[ bootstrap ]

env = []
prepare = "tar --no-same-owner -xf <src_path> -C <tmp_dir>"
configure = "./configure --prefix=/usr"
build = "make"
pkg_create = "make DESTDIR=<pkg_dir> install && rm <pkg_dir>/usr/lib/libz.a"
