[ src ]

url = https://ftp.gnu.org/gnu/<prog>/<prog>-<ver>.tar.gz
src_type = tar
src_dirname = <prog>-<ver>



[ vars ]



[ std ]

env =
prepare = tar --no-same-owner -xf <src_path> -C <tmp_dir>
configure = ./configure
	--prefix=/usr
	--disable-static
	--docdir=/usr/share/doc/mpc
	--disable-dependency-tracking

build = make
pkg_create = make DESTDIR=<pkg_dir> install &&
	rm -r <pkg_dir>/usr/share/



[ musl ]

env =
prepare = tar --no-same-owner -xf <src_path> -C <tmp_dir>
configure = ./configure
	--prefix=/musl
	--bindir=/bin
	--libdir=/lib
	--enable-static
	--disable-shared
	--disable-dependency-tracking

build = make
pkg_create = make DESTDIR=<pkg_dir> install && rm -r <pkg_dir>/musl/share/



[ bootstrap ]

env =
prepare = tar --no-same-owner -xf <src_path> -C <tmp_dir>
configure = ./configure
	--prefix=/usr
	--disable-static
	--docdir=/usr/share/doc/mpc
	--disable-dependency-tracking

build = make
pkg_create = make DESTDIR=<pkg_dir> install
