[ src ]

url = "https://github.com/acmesh-official/acme.sh/archive/refs/tags/<ver>.tar.gz"
src_type = "tar"
src_dirname = "acme.sh-<ver>"



[ std ]

env = []
prepare = "tar --no-same-owner -xf <src_path> -C <tmp_dir>"
configure = ""
build = ""
pkg_create = "mkdir -p <pkg_dir>/usr/bin && cp -a acme.sh <pkg_dir>/usr/bin/"
