[ src ]

url = https://github.com/intel/libva/releases/download/<ver>/libva-<ver>.tar.bz2
src_type = tar
src_dirname = <prog>-<ver>



[ vars ]



[ std ]

env =
prepare = tar --no-same-owner -xf <src_path> -C <tmp_dir>
configure = ./configure
	--prefix=/usr
	--enable-drm
	--disable-x11
	--disable-glx
	--disable-wayland
	--disable-static
	--disable-dependency-tracking

build = make
pkg_create = make DESTDIR=<pkg_dir> install
