[ src ]

url = https://ftp.gnu.org/gnu/<prog>/<prog>-<ver>.tar.bz2
src_type = tar
src_dirname = <prog>-<ver>



[ vars ]



[ std ]

env =
prepare = tar --no-same-owner -xf <src_path> -C <tmp_dir>
configure = autoreconf -fi && ./configure
	--prefix=/usr
	--disable-vcd-info
	--disable-cpp-progs
	--disable-static
	--disable-dependency-tracking

build = make
pkg_create = make DESTDIR=<pkg_dir> install &&
	rm -r <pkg_dir>/usr/share/info/
