[ src ]

url = "https://github.com/intel/intel-vaapi-driver/releases/download/<ver>/intel-vaapi-driver-<ver>.tar.bz2"
src_type = "tar"
src_dirname = "intel-vaapi-driver-<ver>"



[ std ]

env = [ "CFLAGS+=-fcommon" ]
prepare = "tar --no-same-owner -xf <src_path> -C <tmp_dir>"
configure = "./configure
	--prefix=/usr
	--disable-x11
	--disable-wayland
	--disable-dependency-tracking"

build = "make"
pkg_create = "make DESTDIR=<pkg_dir> install"
