[ src ]

url = "https://github.com/hashcat/hashcat/archive/refs/tags/v<ver>.tar.gz"
src_type = "tar"
src_dirname = "<prog>-<ver>"



[ std ]

env = []
prepare = "tar --no-same-owner -xf <src_path> -C <tmp_dir>"
configure = ""
build = "make PREFIX=/usr SHARED=1"
pkg_create = "make PREFIX=/usr SHARED=1 DESTDIR=<pkg_dir> install"
