[ src ]

url = "https://www.lua.org/ftp/lua-<ver>.tar.gz"
src_type = "tar"
src_dirname = "lua-<ver>"



[ std ]

env = []
prepare = "tar --no-same-owner -xf <src_path> -C <tmp_dir>"
configure = "patch -Np1 -i <prog_dir>/patch/liblua.so.patch"

build = "make MYCFLAGS=\"${CFLAGS} -fPIC\" MYLDFLAGS=\"${LDFLAGS}\" linux"
pkg_create = "make
	TO_LIB='liblua.so liblua.so.<ver_short> liblua.so.<ver>'
	INSTALL_DATA='cp -d'
	INSTALL_TOP=${PWD}/install/usr
	INSTALL_MAN=${PWD}/install/usr/share/man/man1
	install &&
	cp -a install/* <pkg_dir>/ &&
	ln -s lua <pkg_dir>/usr/bin/lua<ver_short> &&
	ln -s luac <pkg_dir>/usr/bin/luac<ver_short> &&
	install -Dm644 <prog_dir>/files/lua.pc
		<pkg_dir>/usr/lib/pkgconfig/<prog>.pc &&
	sed -i 's|__VER__|<ver_short>|g'
		<pkg_dir>/usr/lib/pkgconfig/<prog>.pc &&
	sed -i 's|__REL__|<ver>|g' <pkg_dir>/usr/lib/pkgconfig/<prog>.pc &&
	ln -s <prog>.pc <pkg_dir>/usr/lib/pkgconfig/lua.pc &&
	ln -s <prog>.pc <pkg_dir>/usr/lib/pkgconfig/lua<ver_short>.pc &&
	ln -s <prog>.pc <pkg_dir>/usr/lib/pkgconfig/lua-<ver_short>.pc"
