[ src ]

url = https://downloads.sourceforge.net/docbook2X/docbook2X-<ver>.tar.gz
src_type = tar
src_dirname = docbook2X-<ver>



[ vars ]



[ std ]

env =
prepare = tar --no-same-owner -xf <src_path> -C <tmp_dir>
configure = ./configure
	--prefix=/usr
	--mandir=/usr/share/man
	--disable-static
	--disable-dependency-tracking

build = make
pkg_create = make DESTDIR=<pkg_dir> install
