[ src ]

url = "https://xorg.freedesktop.org/archive/individual/util/<prog>-<ver>.tar.gz"
src_type = "tar"
src_dirname = "<prog>-<ver>"



[ std ]

env = []
prepare = "tar --no-same-owner -xf <src_path> -C <tmp_dir>"
configure = "./configure
	--prefix=/usr
	--disable-static
	--disable-dependency-tracking "

build = "make"
pkg_create = "make DESTDIR=<pkg_dir> install"
