[ src ]

url = "https://github.com/TigerVNC/tigervnc/archive/v<ver>.tar.gz"
src_type = "tar"
src_dirname = "<prog>-<ver>"



[ std ]

env = []
prepare = "tar --no-same-owner -xf <src_path> -C <tmp_dir>"

configure = "mkdir build && cd build && cmake
	-G 'Unix Makefiles'
	-D CMAKE_INSTALL_PREFIX=/usr
	-D CMAKE_INSTALL_LIBDIR=/usr/lib
	-D CMAKE_BUILD_TYPE='Release'
	-D BUILD_JAVA=OFF
	-D ENABLE_NLS=OFF
	-D ENABLE_PAM=OFF
	-D INSTALL_SYSTEMD_UNITS=OFF
	-D ENABLE_GNUTLS=OFF
	-Wno-dev
	.."

build = "cd build && make"
pkg_create = "cd build && make DESTDIR=<pkg_dir> install"
