[ src ]

url = "https://github.com/lz4/lz4/archive/refs/tags/v<ver>.tar.gz"
src_type = "tar"
src_dirname = "<prog>-<ver>"



[ std ]

env = []
prepare = "tar --no-same-owner -xf <src_path> -C <tmp_dir>"
configure = ""
build = "make PREFIX=/usr"
pkg_create = "make DESTDIR=<pkg_dir> PREFIX=/usr install &&
	rm <pkg_dir>/usr/lib/liblz4.a"
