[ src ]

url = "https://download.savannah.gnu.org/releases/<prog>/<prog>-<ver>.tar.xz"
src_type = "tar"
src_dirname = "<prog>-<ver>"



[ std ]

env = []
prepare = "tar --no-same-owner -xf <src_path> -C <tmp_dir>"
configure = "./configure
	--prefix=/usr
	--libdir=/usr/lib
	--libexecdir=/usr/lib
	--sysconfdir=/etc
	--enable-shared
	--disable-nls
	--disable-static
	--disable-dependency-tracking"

build = "make"
pkg_create = "make DESTDIR=<pkg_dir> install &&
	rm -r <pkg_dir>/usr/share/{doc,man/man3}/"
