[ src ]

url = https://mirrors.edge.kernel.org/pub/linux/utils/usb/usbutils/usbutils-<ver>.tar.xz
src_type = tar
src_dirname = <prog>-<ver>



[ vars ]



[ std ]

env =
prepare = tar --no-same-owner -xf <src_path> -C <tmp_dir>
configure = autoreconf -vfi &&
	./configure --prefix=/usr
	--datadir=/usr/share/hwdata
	--disable-dependency-tracking

build = make
pkg_create = make DESTDIR=<pkg_dir> install
