[ src ]

url = https://sourceware.org/ftp/lvm2/LVM2.<ver>.tgz
src_type = tar
src_dirname = LVM2.<ver>



[ vars ]



[ std ]

env =
prepare = tar --no-same-owner -xf <src_path> -C <tmp_dir>
configure = ./configure
	--prefix=/usr
	--libdir=/usr/lib
	--exec-prefix=/usr
	--disable-cmdlib
	--disable-use-lvmlockd
	--disable-use-lvmpolld
	--disable-dmeventd
	--disable-dmfilemapd
	--disable-notify-dbus
	--disable-udev-systemd-background-jobs
	--disable-udev_rules
	--disable-udev_sync
	--disable-udev-rule-exec-detection
	--disable-dbus-service
	--disable-selinux
	--disable-static_link
	--disable-nls
	--disable-dependency-tracking

build = make
pkg_create = make DESTDIR=<pkg_dir> install &&
	chmod -Rv u+w <pkg_dir>/ || : &&
	mv <pkg_dir>/etc/ <pkg_dir>/usr/share/



[ musl ]

env = CC="musl-gcc -static"
prepare = tar --no-same-owner -xf <src_path> -C <tmp_dir>
configure = for p in <prog_dir>/patch/<ver>/*.patch; do
		echo ${p} 1>&2 &&
		patch -d . -p1 < ${p} 1>&2 || exit 1;
	done &&
	sed -i 's|@BLKID_LIBS@|-lblkid -luuid|g' make.tmpl.in &&
	sed -i 's|@STATIC_LDFLAGS@||g' make.tmpl.in &&
	sed -i 's|@SELINUX_STATIC_LIBS@||g' make.tmpl.in &&
	sed -i 's|@UDEV_STATIC_LIBS@||g' make.tmpl.in &&
	sed -i 's|@UDEV_STATIC_LIBS@||g' make.tmpl.in &&
	sed -i 's|@BLKID_STATIC_LIBS@||g' make.tmpl.in &&
	./configure
	--host=x86_64-pc-linux-gnu
	--prefix=
	--libdir=/lib
	--enable-static_link
	--enable-pkgconfig
	--disable-cmdlib
	--disable-use-lvmlockd
	--disable-use-lvmpolld
	--disable-notify-dbus
	--disable-readline
	--disable-udev-systemd-background-jobs
	--disable-udev_rules
	--disable-udev_sync
	--disable-udev-rule-exec-detection
	--disable-dbus-service
	--disable-selinux
	--disable-nls
	--disable-dependency-tracking &&
	sed -i 's| TARGETS += | TARGETS = man-generator |g' tools/Makefile &&
	sed -i 's|TARGETS += |TARGETS = |g' tools/Makefile &&
	sed -i 's|TARGETS_DM += |TARGETS_DM = |g' tools/Makefile

build = make
pkg_create = make DESTDIR=<pkg_dir> install &&
	chmod -Rv u+w <pkg_dir>/ || : &&
	mv -v <pkg_dir>/etc/ <pkg_dir>/share/ &&
	mv -v <pkg_dir>/sbin/lvm.static <pkg_dir>/sbin/lvm &&
	mv -v <pkg_dir>/sbin/dmsetup.static <pkg_dir>/sbin/dmsetup &&
	rm -v <pkg_dir>/lib/*.so*

