[ src ]

url = https://github.com/muennich/id3ted/archive/refs/tags/v<ver>.tar.gz
src_type = tar
src_dirname = <prog>-<ver>



[ vars ]



[ std ]

env =
prepare = tar --no-same-owner -xf <src_path> -C <tmp_dir>
configure =
build = make
pkg_create = make PREFIX=<pkg_dir>/usr install
