[ src ]

url = "https://www.sourceware.org/pub/bzip2/bzip2-<ver>.tar.gz"
src_type = "tar"
src_dirname = "<prog>-<ver>"



[ std ]

env = [ "CFLAGS+=-D_FILE_OFFSET_BITS=64" ]
prepare = "tar --no-same-owner -xf <src_path> -C <tmp_dir>"
configure = "sed -i '/^LDFLAGS=$/d' Makefile &&
	sed -i 's/^CFLAGS=/CFLAGS+=/' Makefile &&
	sed -i 's/^CFLAGS=/CFLAGS+=/' Makefile-libbz2_so &&
	sed -i '/^LDFLAGS=/d' Makefile &&
	sed -i 's@\\(ln -s -f \\)$(PREFIX)/bin/@\\1@' Makefile &&
	sed -i 's@(PREFIX)/man@(PREFIX)/share/man@g' Makefile &&
	make -f Makefile-libbz2_so &&
	make clean"

build = "make"
pkg_create = "mkdir -pv <pkg_dir>/usr/{bin,lib} &&
	make PREFIX=<pkg_dir>/usr install &&
	cp -v bzip2-shared <pkg_dir>/usr/bin/bzip2 &&
	cp -av libbz2.so* <pkg_dir>/usr/lib &&
	ln -sv libbz2.so.1.0 <pkg_dir>/usr/lib/libbz2.so &&
	rm -v <pkg_dir>/usr/lib/libbz2.a"



[ init ]

env = [ "CFLAGS+=-D_FILE_OFFSET_BITS=64" ]
prepare = "tar --no-same-owner -xf <src_path> -C <tmp_dir>"
configure = "sed -i '/^LDFLAGS=$/d' Makefile &&
	sed -i 's/^CFLAGS=/CFLAGS+=/' Makefile &&
	sed -i 's/^CFLAGS=/CFLAGS+=/' Makefile-libbz2_so &&
	sed -i '/^LDFLAGS=/d' Makefile &&
	sed -i 's@\\(ln -s -f \\)$(PREFIX)/bin/@\\1@' Makefile &&
	sed -i 's@(PREFIX)/man@(PREFIX)/share/man@g' Makefile &&
	make -f Makefile-libbz2_so &&
	make clean"

build = "make"
pkg_create = "mkdir -pv <pkg_dir>/usr/{bin,lib} &&
	make PREFIX=<pkg_dir>/usr install &&
	cp -v bzip2-shared <pkg_dir>/usr/bin/bzip2 &&
	cp -av libbz2.so* <pkg_dir>/usr/lib &&
	ln -sv libbz2.so.1.0 <pkg_dir>/usr/lib/libbz2.so &&
	rm -v <pkg_dir>/usr/lib/libbz2.a"
