[ src ]

url = "https://ftp.pcre.org/pub/pcre/pcre-<ver>.tar.gz"
src_type = "tar"
src_dirname = "pcre-<ver>"



[ std ]

env = []
prepare = "tar --no-same-owner -xf <src_path> -C <tmp_dir>"
configure = "./configure
	--prefix=/usr
	--enable-pcre2grep-libz
	--enable-pcre2grep-libbz2
	--enable-utf
	--enable-unicode-properties
	--enable-pcre2-16
	--enable-pcre2-32
	--disable-dependency-tracking
	--disable-static
	--disable-cpp"

build = "make"
pkg_create = "make DESTDIR=<pkg_dir> install &&
	rm -r <pkg_dir>/usr/share/{doc,man/man3}/"



[ cpp ]

env = []
prepare = "tar --no-same-owner -xf <src_path> -C <tmp_dir>"
configure = "./configure
	--prefix=/usr
	--enable-pcre2grep-libz
	--enable-pcre2grep-libbz2
	--enable-utf
	--enable-unicode-properties
	--enable-pcre2-16
	--enable-pcre2-32
	--disable-dependency-tracking
	--disable-static
	--enable-cpp"

build = "make"
pkg_create = "make DESTDIR=<pkg_dir> install &&
	rm -r <pkg_dir>/usr/share/{doc,man/man3}/"
