[ src ]

url = https://dl.suckless.org/dwm/dwm-<ver>.tar.gz
src_type = tar
src_dirname = <prog>-<ver>



[ vars ]



[ std ]

env =
prepare = tar --no-same-owner -xf <src_path> -C <tmp_dir>
configure = cp <prog_dir>/files/config.h <build_dir>/config.h
build = PREFIX=/usr make
pkg_create = make PREFIX=/usr DESTDIR=<pkg_dir> install
