[ src ]

url = "https://rsync.samba.org/ftp/rsync/src/rsync-<ver>.tar.gz"
src_type = "tar"
src_dirname = "<prog>-<ver>"



[ std ]

env = []
prepare = "tar --no-same-owner -xf <src_path> -C <tmp_dir>"
configure = "./configure
	--prefix=/usr
	--disable-lz4
	--disable-xxhash
	--disable-locale
	--disable-iconv-open
	--disable-iconv
	--disable-acl-support
	--disable-xattr-support
	--disable-debug"

build = "make"
pkg_create = "make DESTDIR=<pkg_dir> install"
