[ src ]

url = "https://downloads.sourceforge.net/project/<prog>/<prog>/<ver>/<prog>-<ver>.tar.gz"
src_type = "tar"
src_dirname = "<prog>-<ver>"



[ std ]

env = []
prepare = "tar --no-same-owner -xf <src_path> -C <tmp_dir>"
configure = ""
build = "make gdisk sgdisk fixparts"
pkg_create = "mkdir -p <pkg_dir>/usr/bin <pkg_dir>/usr/share/man/man8  &&
	cp -a {,s}gdisk fixparts <pkg_dir>/usr/bin/ &&
	cp -a {{,s}gdisk,fixparts}.8 <pkg_dir>/usr/share/man/man8/"
