[ src ]

url = "https://www.iana.org/time-zones/repository/releases/tzdata<ver>.tar.gz"
src_type = "tar"
src_dirname = "<prog>"



[ std ]

env = []
prepare = "mkdir <tmp_dir>/<prog> &&
	tar --no-same-owner -xf <src_path> -C <tmp_dir>/<prog>"

configure = ""
build = ""
pkg_create = "zonedir='<pkg_dir>/usr/share/zoneinfo' &&
	mkdir -pv <pkg_dir>/etc &&
	mkdir -pv ${zonedir}/{posix,right} &&
	for tz in etcetera southamerica northamerica europe africa antarctica
		asia australasia backward; do
		zic -L /dev/null   -d ${zonedir}       ${tz};
		zic -L /dev/null   -d ${zonedir}/posix ${tz};
		zic -L leapseconds -d ${zonedir}/right ${tz};
	done &&
	cp -v zone.tab zone1970.tab iso3166.tab ${zonedir} &&
	zic -d ${zonedir} -p America/New_York &&
	ln -sfv ../usr/share/zoneinfo/Europe/Warsaw
		<pkg_dir>/etc/localtime"



[ init ]

env = []
prepare = "mkdir <tmp_dir>/<prog> &&
	tar --no-same-owner -xf <src_path> -C <tmp_dir>/<prog>"

configure = ""
build = ""
pkg_create = "zonedir='<pkg_dir>/usr/share/zoneinfo' &&
	mkdir -pv <pkg_dir>/etc &&
	mkdir -pv ${zonedir}/{posix,right} &&
	for tz in etcetera southamerica northamerica europe africa antarctica
		asia australasia backward; do
		zic -L /dev/null   -d ${zonedir}       ${tz};
		zic -L /dev/null   -d ${zonedir}/posix ${tz};
		zic -L leapseconds -d ${zonedir}/right ${tz};
	done &&
	cp -v zone.tab zone1970.tab iso3166.tab ${zonedir} &&
	zic -d ${zonedir} -p America/New_York &&
	ln -sfv ../usr/share/zoneinfo/Europe/Warsaw
		<pkg_dir>/etc/localtime"
