[ src ]

url = "https://github.com/tats/w3m/archive/refs/tags/debian/<ver>.tar.gz"
src_type = "tar"
src_dirname = "w3m-debian-<ver_pkgspec>"



[ std ]

env = [ "LIBS=-ltinfow" ]
prepare = "tar --no-same-owner -xf <src_path> -C <tmp_dir>"
configure = "./configure
	--prefix=/
	--sysconfdir=/etc
	--bindir=/usr/bin
	--libexecdir=/usr/libexec
	--datarootdir=/usr/share
	--mandir=/usr/share/man
	--disable-nls
	--disable-w3mmailer
	--disable-mouse
	--disable-xface
	--disable-dict
	--disable-help-cgi
	--without-x
	--enable-image=fb
	--enable-keymap=w3m
	--enable-nntp
	--enable-gopher
	--enable-unicode
	--with-imagelib=imlib2
	--with-browser=/usr/bin/w3m
	--with-editor=/usr/bin/vim
	--with-ssl
	--with-termlib=ncurses"

build = "make"
pkg_create = "make DESTDIR=<pkg_dir> install &&
	rm -r <pkg_dir>/usr/share/w3m/*{.de.,.ja.}* &&
	rm -r <pkg_dir>/usr/share/man/{de,ja}/"
