[ src ]

url = "https://www.gnupg.org/ftp/gcrypt/gpgme/gpgme-<ver>.tar.bz2"
src_type = "tar"
src_dirname = "<prog>-<ver>"



[ std ]

env = []
prepare = "tar --no-same-owner -xf <src_path> -C <tmp_dir>"

# '--enable-languages=' disables c++
configure = "./configure
	--prefix=/usr
	--enable-languages=
	--disable-dependency-tracking
	--disable-gpg-test
	--disable-gpgsm-test
	--disable-g13-test"

build = "make"
pkg_create = "make DESTDIR=<pkg_dir> install &&
	rm -r <pkg_dir>/usr/share/info/"
