[ src ]

url = https://xorg.freedesktop.org/archive/individual/data/<prog>/<prog>-<ver>.tar.bz2
src_type = tar
src_dirname = <prog>-<ver>



[ vars ]



[ std ]

env =
prepare = tar --no-same-owner -xf <src_path> -C <tmp_dir>
configure = ./configure
	--prefix=/usr
	--with-xkb-base=/usr/share/X11/xkb
	--with-xkb-rules-symlink=xorg
	--enable-compat-rules=yes
	--disable-static
	--disable-dependency-tracking

build = make
pkg_create = make DESTDIR=<pkg_dir> install &&
	rm -r <pkg_dir>/usr/share/locale/
