[ src ]

url = http://ftp.gnu.org/gnu/libtasn1/libtasn1-<ver>.tar.gz
src_type = tar
src_dirname = <prog>-<ver>



[ vars ]



[ std ]

env =
prepare = tar --no-same-owner -xf <src_path> -C <tmp_dir>
configure = ./configure
	--prefix=/usr
	--disable-dependency-tracking
	--disable-static
	--disable-gtk-doc-html

build = make
pkg_create = make DESTDIR=<pkg_dir> install &&
	rm -r <pkg_dir>/usr/share/{info,man/man3}/
