[ src ]

url = "https://downloads.sourceforge.net/smartmontools/smartmontools-<ver>.tar.gz"
src_type = "tar"
src_dirname = "<prog>-<ver>"



[ std ]

env = []
prepare = "tar --no-same-owner -xf <src_path> -C <tmp_dir>"
configure = "./configure
	--prefix=/usr
	--disable-dependency-tracking
	--with-gnupg=no
	--with-selinux=no
	--with-libcap-ng=no
	--with-libsystemd=no
	--with-systemdsystemunitdir=no
	--with-systemdenvfile=no"

build = "make"
pkg_create = "make DESTDIR=<pkg_dir> install &&
	mv <pkg_dir>/usr/etc/ <pkg_dir>/usr/share/ &&
	rm -r <pkg_dir>/usr/share/doc/"
