[ src ]

url = "http://xmlsoft.org/sources/libxml2-<ver>.tar.gz"
src_type = "tar"
src_dirname = "<prog>-<ver>"



[ std ]

env = []
prepare = "tar --no-same-owner -xf <src_path> -C <tmp_dir>"
configure = "./configure
	--prefix=/usr
	--disable-dependency-tracking
	--disable-static
	--with-history
	--with-python=/usr/bin/python3
	--without-threads
	--without-icu"

build = "make"
pkg_create = "make DESTDIR=<pkg_dir> install &&
	rm -r <pkg_dir>/usr/share/{doc,gtk-doc}/"
