[ src ]

url = "https://ffmpeg.org/releases/ffmpeg-<ver>.tar.xz"
src_type = "tar"
src_dirname = "<prog>-<ver>"



[ std ]

env = []
prepare = "tar --no-same-owner -xf <src_path> -C <tmp_dir>"

# sdl2 is required for ffplay
configure = "./configure
	--prefix=/usr
	--enable-shared
	--disable-static
	--disable-debug

	--enable-gpl
	--enable-nonfree
	--enable-version3
	--enable-pic

	--disable-gnutls
	--disable-libtls
	--disable-mbedtls
	--disable-chromaprint
	--disable-sdl2

	--enable-alsa
	--enable-fontconfig
	--enable-network
	--enable-openssl
	--enable-libass
	--enable-libbluray
	--enable-libcdio
	--enable-libdav1d
	--enable-libdrm
	--enable-libfdk-aac
	--enable-libfontconfig
	--enable-libfreetype
	--enable-libfribidi
	--enable-libmodplug
	--enable-libmp3lame
	--enable-libopus
	--enable-libv4l2
	--enable-libvorbis
	--enable-libwebp
	--enable-libx264
	--enable-libxml2
	--enable-libxvid
	--enable-vaapi"


build = "make && make doc/ff{mpeg,play}.1"
pkg_create = "make DESTDIR=<pkg_dir> install install-man"
