[ src ]

url = "https://ftp.gnu.org/gnu/<prog>/<prog>-<ver>.tar.gz"
src_type = "tar"
src_dirname = "<prog>-<ver>"



[ std ]

env = []
prepare = "tar --no-same-owner -xf <src_path> -C <tmp_dir>"
configure = "./configure
	--prefix=/usr
	--sysconfdir=/etc
	--with-ssl=openssl
	--enable-assert
	--disable-dependency-tracking
	--disable-nls
	--disable-xattr"

build = "make"
pkg_create = "make DESTDIR=<pkg_dir> install &&
	rm -r <pkg_dir>/usr/share/info/"
