[ src ]

url = "https://download.tuxfamily.org/chrony/chrony-<ver>.tar.gz"
src_type = "tar"
src_dirname = "<prog>-<ver>"



[ std ]

env = []
prepare = "tar --no-same-owner -xf <src_path> -C <tmp_dir>"
configure = "./configure
	--prefix=/usr
	--enable-privdrop
	--with-libcap

	--disable-readline
	--disable-nts
	--disable-cmdmon
	--without-editline
	--without-nss
	--without-gnutls"

build = "make"
pkg_create = "make DESTDIR=<pkg_dir> install"
