[ src ]

url = "https://pypi.io/packages/source/c/<prog>/<prog>-<ver>.tar.gz"
src_type = "tar"
src_dirname = "<prog>-<ver>"



[ std ]

env = [ "PYTHONHASHSEED=0", "CRYPTOGRAPHY_DONT_BUILD_RUST=1"]
prepare = "tar --no-same-owner -xf <src_path> -C <tmp_dir>"
configure = "sed -e 's|from setuptools_rust import RustExtension|pass|'
		-e '/setup_requires/d'  -i setup.py"

build = "python setup.py build"
pkg_create = "python setup.py install
		--root=<pkg_dir>
		--prefix=/usr
		--optimize=1
		--skip-build &&
	find <pkg_dir> -depth -type f -name '*.py[co]' -delete
		-o -type d -name __pycache__ -delete
	"
