[ src ]

url = "https://gitlab.xiph.org/xiph/libao/-/archive/<ver>/libao-<ver>.tar.gz"
src_type = "tar"
src_dirname = "<prog>-<ver>"



[ std ]

env = []
prepare = "tar --no-same-owner -xf <src_path> -C <tmp_dir>"
configure = "autoreconf -vfi && ./configure
	--prefix=/usr
	--enable-alsa-mmap
	--disable-static
	--disable-dependency-tracking"

build = "make"
pkg_create = "make DESTDIR=<pkg_dir> install &&
	rm -r <pkg_dir>/usr/share/doc/"
