[ src ]

url = "https://ftp.gnu.org/gnu/<prog>/<prog>-<ver>.tar.gz"
src_type = "tar"
src_dirname = "<prog>-<ver>"



[ std ]

env = []
prepare = "tar --no-same-owner -xf <src_path> -C <tmp_dir>"
configure = "./configure
	--prefix=/usr
	--sysconfdir=/etc
	--bindir=/bin
	--sbindir=/sbin
	--mandir=/usr/share/man
	--docdir=/usr/share/doc/bash

	--enable-mem-scramble
	--enable-readline
	--with-installed-readline
	--with-curses

	--without-bash-malloc
	--disable-threads
	--disable-nls
	--disable-debugger
	--disable-directory-stack
	--disable-disabled-builtins
	--disable-net-redirections
	--disable-progcomp
	--disable-profiling"

# parallel build workarounds
build = "make y.tab.c && make builtins/libbuiltins.a && make"

pkg_create = "make DESTDIR=<pkg_dir> install &&
	rm -f <pkg_dir>/bin/bashbug <pkg_dir>/usr/share/man/man1/*bug* &&
	rm -r <pkg_dir>/usr/lib <pkg_dir>/usr/share/{doc,info}/"



[ musl ]

env = [ "CC=musl-gcc -static" ]
prepare = "tar --no-same-owner -xf <src_path> -C <tmp_dir>"
configure = "./configure
	--prefix=
	--sysconfdir=/etc
	--mandir=/share/man
	--docdir=share/doc/bash

	--enable-mem-scramble
	--enable-readline
	--with-installed-readline
	--with-curses

	--without-bash-malloc
	--disable-threads
	--disable-nls
	--disable-debugger
	--disable-directory-stack
	--disable-disabled-builtins
	--disable-net-redirections
	--disable-progcomp
	--disable-profiling"

# parallel build workarounds
build = "make y.tab.c && make builtins/libbuiltins.a && make"

pkg_create = "make DESTDIR=<pkg_dir> install &&
	rm <pkg_dir>/bin/bashbug <pkg_dir>/share/man/man1/*bug* &&
	rm -r <pkg_dir>/{share,lib} <pkg_dir>/share/doc/"



[ bootstrap_cross ]

env = [ "MAKEFLAGS=-j1" ]
prepare = "tar --no-same-owner -xf <src_path> -C <tmp_dir>"
configure = "./configure
	--prefix=/usr
	--bindir=/bin
	--sbindir=/sbin
	--build=$(support/config.guess)
	--host=${TARGET_TRIPLET}
	--without-curses
	--without-bash-malloc"

build = "make"
pkg_create = "make DESTDIR=<pkg_dir> install &&
	ln -sfv bash <pkg_dir>/usr/bin/sh &&
	rm -f <pkg_dir>/bin/bashbug"



[ bootstrap ]

env = []
prepare = "tar --no-same-owner -xf <src_path> -C <tmp_dir>"
configure = "./configure
	--prefix=/usr
	--bindir=/bin
	--sbindir=/sbin
	--docdir=/usr/share/doc/bash
	--without-curses
	--without-bash-malloc
	--disable-nls
	--with-installed-readline"

# parallel build workarounds
build = "make y.tab.c && make builtins/libbuiltins.a && make"
pkg_create = "make DESTDIR=<pkg_dir> install &&
	rm -vf <pkg_dir>/bin/bashbug"
