[ src ]

url = "https://github.com/mitmproxy/mitmproxy/archive/v<ver>/mitmproxy-<ver>.tar.gz"
src_type = "tar"
src_dirname = "<prog>-<ver>"



[ std ]

env = []
prepare = "tar --no-same-owner -xf <src_path> -C <tmp_dir>"
configure = ""
build = "python setup.py build"
pkg_create = "python3 setup.py install
		--root=<pkg_dir> --optimize=1 --skip-build &&
	find <pkg_dir> -depth -type f -name '*.py[co]' -delete
		-o -type d -name __pycache__ -delete"
