[ src ]

url = https://download.savannah.gnu.org/releases/libunwind/libunwind-<ver>.tar.gz
src_type = tar
src_dirname = <prog>-<ver>



[ vars ]



[ std ]

env =
prepare = tar --no-same-owner -xf <src_path> -C <tmp_dir>
configure = ./configure
	--prefix=/usr
	--disable-nls
	--disable-static
	--disable-dependency-tracking

build = make
pkg_create = make DESTDIR=<pkg_dir> install
