[ src ]

url = "https://libzip.org/download/libzip-<ver>.tar.xz"
src_type = "tar"
src_dirname = "<prog>-<ver>"



[ std ]

env = []
prepare = "tar --no-same-owner -xf <src_path> -C <tmp_dir>"

configure = "mkdir build && cd build && cmake
	-D CMAKE_INSTALL_PREFIX=/usr
	-D CMAKE_INSTALL_LIBDIR=/usr/lib
	-D CMAKE_BUILD_TYPE='Release'
	-D BUILD_EXAMPLES=OFF
	-D BUILD_REGRESS=OFF
	-D ENABLE_COMMONCRYPTO=OFF
	-D ENABLE_GNUTLS=OFF
	-D ENABLE_MBEDTLS=OFF
	-D ENABLE_OPENSSL=OFF
	-D ENABLE_WINDOWS_CRYPTO=OFF
	.."

build = "cd build && make"
pkg_create = "cd build && make DESTDIR=<pkg_dir> install"
