[ src ]

url = https://github.com/google/brotli/archive/refs/tags/v<ver>.tar.gz
src_type = tar
src_dirname = <prog>-<ver>



[ vars ]



[ std ]

env =
prepare = tar --no-same-owner -xf <src_path> -C <tmp_dir>
configure = mkdir build && cd build && cmake
	-D CMAKE_BUILD_TYPE=Release
	-D CMAKE_INSTALL_PREFIX=/usr
	-D CMAKE_INSTALL_LIBDIR=lib
	-D BUILD_SHARED_LIBS=True
	-D BUILD_STATIC_LIBS=False
	..

build = cd build && make
pkg_create = cd build && make DESTDIR=<pkg_dir> install &&
	rm -r <pkg_dir>/usr/lib/*.a
