[ src ]

url = https://github.com/joncampbell123/dosbox-x/archive/refs/tags/dosbox-x-v<ver>.tar.gz
src_type = tar
src_dirname = <prog>-<prog>-v<ver>



[ vars ]



[ std ]

env =
prepare = tar --no-same-owner -xf <src_path> -C <tmp_dir>
configure = ./autogen.sh && ./configure
	--prefix=/usr
	--disable-static
	--disable-dependency-tracking
	--disable-x11
	--disable-alsatest
	--disable-printer
	--disable-mt32
	--disable-screenshots
	--disable-avcodec
	--enable-opengl
	--enable-d3d9
	--enable-d3d-shaders
	--enable-sdl2

build = make
pkg_create = make DESTDIR=<pkg_dir> install &&
	rm -r <pkg_dir>/usr/share/{applications,icons,metainfo}/
