[ src ]

url = https://github.com/bettercap/bettercap/archive/refs/tags/v<ver>.tar.gz
src_type = tar
src_dirname = <prog>-<ver>



[ vars ]



[ std ]

env =
prepare = tar --no-same-owner -xf <src_path> -C <tmp_dir>
configure =
build = export GOFLAGS='-buildmode=pie -ldflags=-linkmode=external
		-trimpath -mod=readonly -modcacherw' &&
	export GO11MODULE=on &&
	export CGO_CFLAGS="${CFLAGS}" &&
	export CGO_LDFLAGS="${LDFLAGS}" &&
	export GOPATH=/usr/lib/go-pkg &&
	go build

pkg_create = mkdir -p <pkg_dir>/usr/bin && cp bettercap <pkg_dir>/usr/bin/
