[ src ]

url = "https://mj.ucw.cz/download/linux/pci/pciutils-<ver>.tar.gz"
src_type = "tar"
src_dirname = "<prog>-<ver>"



[ std ]

env = []
prepare = "tar --no-same-owner -xf <src_path> -C <tmp_dir>"
configure = ""
build = "make
	ZLIB=no
	SHARED=yes
	STATIC=no
	PREFIX=/usr
	MANDIR=/usr/share/man
	SBINDIR=/usr/bin"

pkg_create = "make
	DESTDIR=<pkg_dir>
	ZLIB=no
	SHARED=yes
	STATIC=no
	PREFIX=/usr
	MANDIR=/usr/share/man
	SBINDIR=/usr/bin
	install install-lib"
