[ src ]

url = http://www.dest-unreach.org/socat/download/socat-<ver>.tar.gz
src_type = tar
src_dirname = <prog>-<ver>



[ vars ]



[ std ]

env =
prepare = tar --no-same-owner -xf <src_path> -C <tmp_dir>
configure = ./configure
	--prefix=/usr
	--disable-ip6

build = make
pkg_create = make DESTDIR=<pkg_dir> install
