[ src ]

url = "https://github.com/Tomas-M/iotop/archive/refs/tags/v<ver>.tar.gz"
src_type = "tar"
src_dirname = "<prog>-<ver>"



[ std ]

env = []
prepare = "tar --no-same-owner -xf <src_path> -C <tmp_dir>"
configure = ""
build = "make"
pkg_create = "make DESTDIR=<pkg_dir> install"
