[ src ]

url = "https://xorg.freedesktop.org/releases/individual/lib/libICE-<ver>.tar.bz2"
src_type = "tar"
src_dirname = "libICE-<ver>"



[ std ]

env = []
prepare = "tar --no-same-owner -xf <src_path> -C <tmp_dir>"
configure = "./configure
	--prefix=/usr
	--sysconfdir=/etc
	--disable-static
	--disable-dependency-tracking"

build = "make"
pkg_create = "make DESTDIR=<pkg_dir> install &&
	rm -r <pkg_dir>/usr/share/"
