[ src ]

url = https://xorg.freedesktop.org/archive/individual/driver/<prog>-<ver>.tar.bz2
src_type = tar
src_dirname = <prog>-<ver>



[ vars ]



[ std ]

env = LDFLAGS= CFLAGS=
prepare = tar --no-same-owner -xf <src_path> -C <tmp_dir>
configure = patch -p1 -i <prog_dir>/patch/xorg-server-21.1.patch &&
	./configure
	--prefix=/usr
	--disable-static
	--disable-dependency-tracking

build = make
pkg_create = make DESTDIR=<pkg_dir> install
