[ src ]

url = "https://github.com/rockdaboot/libpsl/releases/download/<ver>/<prog>-<ver>.tar.gz"
src_type = "tar"
src_dirname = "<prog>-<ver>"



[ std ]

env = []
prepare = "tar --no-same-owner -xf <src_path> -C <tmp_dir>"
configure = "./configure
	--prefix=/usr
	--disable-static
	--disable-dependency-tracking
	--disable-gtk-doc"

build = "make"
pkg_create = "make DESTDIR=<pkg_dir> install"
