[ src ]

url = "https://nlnetlabs.nl/downloads/unbound/unbound-<ver>.tar.gz"
src_type = "tar"
src_dirname = "<prog>-<ver>"



[ std ]

env = []
prepare = "tar --no-same-owner -xf <src_path> -C <tmp_dir>"
configure = "./configure
	--prefix=/usr
	--sysconfdir=/etc
	--enable-pie
	--enable-relro-now
	--with-pidfile=/run/pid/unbound.pid
	--disable-static
	--disable-systemd
	--disable-gost
	--disable-dsa
	--disable-ed448
	--disable-dnscrypt
	--disable-dnstap
	--disable-cachedb
	--disable-ipsecmod
	--disable-ipset
	--without-pythonmodule"

build = "make"
pkg_create = "make DESTDIR=<pkg_dir> install &&
	rm -r <pkg_dir>/usr/share/man/man3/ &&
	mkdir -p <pkg_dir>/usr/share/unbound/ && 
	mv <pkg_dir>/etc <pkg_dir>/usr/share/"
