[ src ]

url = "https://www.gnupg.org/ftp/gcrypt/npth/npth-<ver>.tar.bz2"
src_type = "tar"
src_dirname = "<prog>-<ver>"



[ std ]

env = []
prepare = "tar --no-same-owner -xf <src_path> -C <tmp_dir>"
configure = "./configure
	--prefix=/usr
	--disable-dependency-tracking
	--disable-tests"

build = "make"
pkg_create = "make DESTDIR=<pkg_dir> install"
