[ src ]

url = https://releases.pagure.org/libaio/libaio-<ver>.tar.gz
src_type = tar
src_dirname = <prog>-<ver>



[ vars ]



[ std ]

env =
prepare = tar --no-same-owner -xf <src_path> -C <tmp_dir>
configure =
build = make
pkg_create = make DESTDIR=<pkg_dir> install &&
	rm <pkg_dir>/usr/lib/libaio.a



[ musl ]

env = CC="musl-gcc -static"
prepare = tar --no-same-owner -xf <src_path> -C <tmp_dir>
configure =
build = make
pkg_create = make DESTDIR=<pkg_dir> prefix= install &&
	rm <pkg_dir>/lib/libaio.so*
