[ src ]

url = golang.org/x/net
src_type = go-mod
src_dirname =



[ vars ]



[ std ]

env =
prepare = mkdir -p <pkg_dir>/usr/lib/go-pkg/
configure =
build =
pkg_create = cp -a <src_dir>/<ver>/* <pkg_dir>/usr/lib/go-pkg/ &&
	chmod -R u+w <pkg_dir>/ <src_dir>/
