[ src ]

url = https://www.netfilter.org/pub/libnfnetlink/libnfnetlink-<ver>.tar.bz2
src_type = tar
src_dirname = <prog>-<ver>



[ vars ]



[ std ]

env =
prepare = tar --no-same-owner -xf <src_path> -C <tmp_dir>
configure = ./configure --prefix=/usr --disable-dependency-tracking
build = make
pkg_create = make DESTDIR=<pkg_dir> install
