[ src ]

url = "https://github.com/nghttp2/nghttp2/releases/download/v<ver>/nghttp2-<ver>.tar.bz2"
src_type = "tar"
src_dirname = "<prog>-<ver>"



[ std ]

env = []
prepare = "tar --no-same-owner -xf <src_path> -C <tmp_dir>"
configure = "./configure
	--prefix=/usr
	--disable-dependency-tracking
	--enable-lib-only
	--with-boost=no"

build = "make"
pkg_create = "make DESTDIR=<pkg_dir> install"
