[ src ]

url = "https://www.alsa-project.org/files/pub/lib/alsa-lib-<ver>.tar.bz2"
src_type = "tar"
src_dirname = "<prog>-<ver>"



[ std ]

env = []
prepare = "tar --no-same-owner -xf <src_path> -C <tmp_dir>"
configure = "autoreconf -fi && ./configure
	--prefix=/usr
	--without-debug
	--disable-dependency-tracking"

build = "make"
pkg_create = "make DESTDIR=<pkg_dir> install"
