[ src ]

url = "https://github.com/WorMzy/vlock"
src_type = "git"
src_dirname = "<prog>"



[ std ]

env = []
prepare = "cp -a <src_path> <tmp_dir> && cd <build_dir> &&
	git checkout <ver_short>"

configure = "./configure --prefix=/usr --disable-plugins --enable-shadow"
build = "make"
pkg_create = "make DESTDIR=<pkg_dir> install"
