[ src ]

url = "https://freedesktop.org/software/libinput/libinput-<ver>.tar.xz"
src_type = "tar"
src_dirname = "libinput-<ver>"



[ std ]

env = []
prepare = "tar --no-same-owner -xf <src_path> -C <tmp_dir>"
configure = "meson
	--prefix=/usr
	--libdir=lib
	-D debug-gui=false
	-D libwacom=false
	-D b_lto=false
	-D udev-dir=/usr/lib/udev
	-D tests=false
	-D documentation=false
	-D zshcompletiondir=no
	build"

build = "ninja -C build all"
pkg_create = "DESTDIR=<pkg_dir> ninja -C build install &&
	rmdir <pkg_dir>/etc/libinput/ <pkg_dir>/etc/"
