[ src ]

url = "https://github.com/libexif/libexif/archive/libexif-<ver_pkgspec>-release.tar.gz"
src_type = "tar"
src_dirname = "libexif-<prog>-<ver_pkgspec>-release"



[ std ]

env = []
prepare = "tar --no-same-owner -xf <src_path> -C <tmp_dir>"
configure = "autoreconf -fi && ./configure
	--prefix=/usr
	--disable-nls
	--disable-docs
	--disable-static
	--disable-dependency-tracking"

build = "make"
pkg_create = "make DESTDIR=<pkg_dir> install &&
	rm -r <pkg_dir>/usr/share/"
