[ src ]

url = "https://ftp.gnu.org/gnu/binutils/binutils-<ver>.tar.xz"
src_type = "tar"
src_dirname = "<prog>-<ver>"



[ std ]

env = []
prepare = "tar --no-same-owner -xf <src_path> -C <tmp_dir>"
configure = "mkdir -p build && cd build && ../configure
	--prefix=/usr
	--enable-gold
	--enable-ld=default
	--enable-plugins
	--enable-shared
	--disable-nls
	--disable-werror
	--enable-64-bit-bfd
	--with-system-zlib"

build = "cd build && make tooldir=/usr"
pkg_create = "cd build && make DESTDIR=<pkg_dir> tooldir=/usr install &&
	rm -v <pkg_dir>/usr/lib/lib{bfd,ctf,ctf-nobfd,opcodes}.a &&
	rm -r <pkg_dir>/usr/share/info/"



[ bootstrap_1_cross ]

env = []
prepare = "tar --no-same-owner -xf <src_path> -C <tmp_dir>"
configure = "mkdir -p build && cd build && ../configure
	--prefix=/tools
	--with-sysroot=<root_dir>
	--target=${TARGET_TRIPLET}
	--enable-gprofng=no
	--disable-nls
	--disable-werror"

build = "cd build && make"
pkg_create = "cd build && make DESTDIR=<pkg_dir> install"



[ bootstrap_2_cross ]


# binutils is shipped with an outdated libtool copy. It lacks sysroot support
# so the produced binaries will be mistakenly linked to libraries from
# the host distro. sed here is a workaround for that.
# use "MAKEFLAGS=j1" if errors show up
env = [ "CFLAGS=", "LDFLAGS=" ]
prepare = "tar --no-same-owner -xf <src_path> -C <tmp_dir>"
configure = "sed '6009s/$add_dir//' -i ltmain.sh &&
	mkdir -p build && cd build && ../configure
	--prefix=/usr
	--build=$(../config.guess)
	--host=${TARGET_TRIPLET}
	--disable-nls
	--enable-shared
	--enable-gprofng=no
	--disable-werror
	--disable-nls
	--enable-64-bit-bfd"

build = "cd build && make"
pkg_create = "cd build && make DESTDIR=<pkg_dir> install"



[ bootstrap ]

env = []
prepare = "tar --no-same-owner -xf <src_path> -C <tmp_dir>"
configure = "mkdir -p build && cd build && ../configure
	--prefix=/usr
	--enable-gold
	--enable-ld=default
	--enable-plugins
	--enable-shared
	--disable-nls
	--disable-werror
	--enable-64-bit-bfd
	--with-system-zlib"

build = "cd build && make tooldir=/usr"
pkg_create = "cd build && make DESTDIR=<pkg_dir> tooldir=/usr install &&
	rm -v <pkg_dir>/usr/lib/lib{bfd,ctf,ctf-nobfd,opcodes}.a"
