[ src ]

url = "https://www.kraxel.org/releases/input/input-<ver>.tar.gz"
src_type = "tar"
src_dirname = "input-<ver>"



[ std ]

env = [ "prefix=/usr"]
prepare = "tar --no-same-owner -xf <src_path> -C <tmp_dir>"
configure = ""
build = "make"
pkg_create = "make DESTDIR=<pkg_dir> install"
