[ src ]

url = https://imagemagick.org/download/ImageMagick-<ver>.tar.xz
src_type = tar
src_dirname = ImageMagick-<ver>



[ vars ]



[ std ]

env =
prepare = tar --no-same-owner -xf <src_path> -C <tmp_dir>
configure = ./configure
	--prefix=/usr
	--sysconfdir=/etc
	--disable-static
	--enable-shared
	--disable-dependency-tracking
	--with-modules
	--without-perl
	--without-autotrace
	--without-dps
	--without-fftw
	--without-fpx
	--without-gcc-arch
	--without-gvc

build = make
pkg_create = make DESTDIR=<pkg_dir> install &&
	rm -r <pkg_dir>/usr/share/doc/
#rm <pkg_dir>/usr/share/ImageMagick/fr*
