[ src ]

url = "https://xorg.freedesktop.org/archive/individual/proto/xorgproto-<ver>.tar.gz"
src_type = "tar"
src_dirname = "xorgproto-<ver>"



[ std ]

env = []
prepare = "tar --no-same-owner -xf <src_path> -C <tmp_dir>"
configure = "./configure
	--prefix=/usr
	--disable-dependency-tracking
	"

build = "make"
pkg_create = "make DESTDIR=<pkg_dir> install &&
	rm -r <pkg_dir>/usr/share/doc/"
