[ src ]

url = https://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
https://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
https://dl-cdn.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz

src_type = alpine
src_dirname = rootfs



[ vars ]



[ std ]

env = ADD_PROGS=loksh
prepare = apk update
configure =
build = apk add --no-chown <prog> ${ADD_PROGS}

# fontconfig and firefox need to have links to be relative
pkg_create = cp -av <build_dir>/rootfs/* <pkg_dir>/ &&
	for f in <pkg_dir>/etc/fonts/conf.d/*.conf; do
		fbase="$(basename "${f}")";
		ln -sf "../../../usr/share/fontconfig/conf.avail/${fbase}"
			"<pkg_dir>/etc/fonts/conf.d/${fbase}";
	done &&
	ln -sf ../../usr/lib/firefox/firefox <pkg_dir>/usr/bin/firefox &&
	cd <pkg_dir> && chmod 755 proc && rm -rf {media,opt,srv,var/*}
