[ src ]

url = ""
src_type = "tar"
src_dirname = ""



[ std ]

env = []
prepare = ""
configure = ""
build = ""
pkg_create = "install -v -d -m755 <pkg_dir>/etc/xml &&
	xmlcatalog --noout --create <pkg_dir>/etc/xml/docbook &&

	xmlcatalog --noout --add 'public'
		'-//OASIS//DTD DocBook XML V<ver>//EN'
		'http://www.oasis-open.org/docbook/xml/<ver>/docbookx.dtd'
		<pkg_dir>/etc/xml/docbook &&
	xmlcatalog --noout --add 'public'
		'-//OASIS//DTD DocBook XML CALS Table Model V<ver>//EN'
		'file:///usr/share/xml/docbook/xml-dtd-<ver>/calstblx.dtd'
		<pkg_dir>/etc/xml/docbook &&
	xmlcatalog --noout --add 'public'
		'-//OASIS//DTD XML Exchange Table Model 19990315//EN'
		'file:///usr/share/xml/docbook/xml-dtd-<ver>/soextblx.dtd'
		<pkg_dir>/etc/xml/docbook &&
	xmlcatalog --noout --add 'public'
		'-//OASIS//ELEMENTS DocBook XML Information Pool V<ver>//EN'
		'file:///usr/share/xml/docbook/xml-dtd-<ver>/dbpoolx.mod'
		<pkg_dir>/etc/xml/docbook &&
	xmlcatalog --noout --add 'public'
		'-//OASIS//ELEMENTS DocBook XML Document Hierarchy V<ver>//EN'
		'file:///usr/share/xml/docbook/xml-dtd-<ver>/dbhierx.mod'
		<pkg_dir>/etc/xml/docbook &&
	xmlcatalog --noout --add 'public'
		'-//OASIS//ELEMENTS DocBook XML HTML Tables V<ver>//EN'
		'file:///usr/share/xml/docbook/xml-dtd-<ver>/htmltblx.mod'
		<pkg_dir>/etc/xml/docbook &&
	xmlcatalog --noout --add 'public'
		'-//OASIS//ENTITIES DocBook XML Notations V<ver>//EN'
		'file:///usr/share/xml/docbook/xml-dtd-<ver>/dbnotnx.mod'
		<pkg_dir>/etc/xml/docbook &&
	xmlcatalog --noout --add 'public'
		'-//OASIS//ENTITIES DocBook XML Character Entities V<ver>//EN'
		'file:///usr/share/xml/docbook/xml-dtd-<ver>/dbcentx.mod'
		<pkg_dir>/etc/xml/docbook &&
	xmlcatalog --noout --add 'public'
		'-//OASIS//ENTITIES DocBook XML Additional General Entities V<ver>//EN'
		'file:///usr/share/xml/docbook/xml-dtd-<ver>/dbgenent.mod'
		<pkg_dir>/etc/xml/docbook &&
	xmlcatalog --noout --add 'rewriteSystem'
		'http://www.oasis-open.org/docbook/xml/<ver>'
		'file:///usr/share/xml/docbook/xml-dtd-<ver>'
		<pkg_dir>/etc/xml/docbook &&
	xmlcatalog --noout --add 'rewriteURI'
		'http://www.oasis-open.org/docbook/xml/<ver>'
		'file:///usr/share/xml/docbook/xml-dtd-<ver>'
		<pkg_dir>/etc/xml/docbook &&

	xmlcatalog --noout --create <pkg_dir>/etc/xml/catalog &&

	xmlcatalog --noout --add 'delegatePublic'
		'-//OASIS//ENTITIES DocBook XML'
		'file:///etc/xml/docbook'
		<pkg_dir>/etc/xml/catalog &&
	xmlcatalog --noout --add 'delegatePublic'
		'-//OASIS//DTD DocBook XML'
		'file:///etc/xml/docbook'
		<pkg_dir>/etc/xml/catalog &&
	xmlcatalog --noout --add 'delegateSystem'
		'http://www.oasis-open.org/docbook/'
		'file:///etc/xml/docbook'
		<pkg_dir>/etc/xml/catalog &&
	xmlcatalog --noout --add 'delegateURI'
		'http://www.oasis-open.org/docbook/'
		'file:///etc/xml/docbook'
		<pkg_dir>/etc/xml/catalog


	xmlcatalog --noout --add 'rewriteSystem'
		'https://cdn.docbook.org/release/xsl-nons/<ver>'
		'/usr/share/xml/docbook/xsl-stylesheets-nons-<ver>'
		<pkg_dir>/etc/xml/catalog &&

	xmlcatalog --noout --add 'rewriteURI'
		'https://cdn.docbook.org/release/xsl-nons/<ver>'
		'/usr/share/xml/docbook/xsl-stylesheets-nons-<ver>'
		<pkg_dir>/etc/xml/catalog &&

	xmlcatalog --noout --add 'rewriteSystem'
		'https://cdn.docbook.org/release/xsl-nons/current'
		'/usr/share/xml/docbook/xsl-stylesheets-nons-<ver>'
		<pkg_dir>/etc/xml/catalog &&

	xmlcatalog --noout --add 'rewriteURI'
		'https://cdn.docbook.org/release/xsl-nons/current'
		'/usr/share/xml/docbook/xsl-stylesheets-nons-<ver>'
		<pkg_dir>/etc/xml/catalog &&

	xmlcatalog --noout --add 'rewriteSystem'
		'http://docbook.sourceforge.net/release/xsl/current'
		'/usr/share/xml/docbook/xsl-stylesheets-nons-<ver>'
		<pkg_dir>/etc/xml/catalog &&

	xmlcatalog --noout --add 'rewriteURI'
		'http://docbook.sourceforge.net/release/xsl/current'
		'/usr/share/xml/docbook/xsl-stylesheets-nons-<ver>'
		<pkg_dir>/etc/xml/catalog
	"
