[ src ]

url = https://mesa.freedesktop.org/archive/demos/mesa-demos-<ver>.tar.bz2
src_type = tar
src_dirname = <prog>-<ver>



[ vars ]



[ std ]

env =
prepare = tar --no-same-owner -xf <src_path> -C <tmp_dir>
configure = meson --prefix=/usr
	--libdir=lib
	--buildtype=release
	-D egl=enabled
	-D gles1=disabled
	-D gles2=enabled
	-D osmesa=enabled
	-D libdrm=enabled
	-D x11=enabled
	-D wayland=disabled
	build

build = ninja -C build all
pkg_create = DESTDIR=<pkg_dir> ninja -C build install
