[ src ]

url = https://master.dl.sourceforge.net/project/lirc/LIRC/<ver>/lirc-<ver>.tar.gz
src_type = tar
src_dirname = <prog>-<ver>



[ vars ]



[ std ]

env =
prepare = tar --no-same-owner -xf <src_path> -C <tmp_dir>
configure = for patch in <prog_dir>/patch/*.patch; do
		patch -p1 -i "${patch}";
	done &&
	./autogen.sh &&
	./configure
		--prefix=/usr
		--sysconfdir=/etc
		--localstatedir=/var
		--enable-devinput
		--enable-uinput
		--disable-static
		--disable-dependency-tracking

build = make
pkg_create = make DESTDIR=<pkg_dir> install &&
	mv <pkg_dir>/etc/ <pkg_dir>/usr/share/lirc/ &&

	rm -r <pkg_dir>/var/ <pkg_dir>/usr/share/doc/
		<pkg_dir>/usr/lib/python3.9/site-packages/*/__pycache__/
		<pkg_dir>/usr/share/lirc/python-pkg/
		<pkg_dir>usr/share/lirc/lirc-0.10.1.tar.gz
