[ src ]

url = "https://github.com/westes/flex/releases/download/v<ver>/flex-<ver>.tar.gz"
src_type = "tar"
src_dirname = "<prog>-<ver>"



[ std ]

env = []
prepare = "tar --no-same-owner -xf <src_path> -C <tmp_dir>"
configure = "./configure
	--prefix=/usr
	--disable-static
	--disable-dependency-tracking
	--docdir=/usr/share/doc/flex"

build = "make"
pkg_create = "make DESTDIR=<pkg_dir> install &&
	ln -sv flex <pkg_dir>/usr/bin/lex &&
	rm -r <pkg_dir>/usr/share/{doc,info,locale}/"



[ init ]

env = []
prepare = "tar --no-same-owner -xf <src_path> -C <tmp_dir>"
configure = "./configure
	--prefix=/usr
	--disable-static
	--disable-dependency-tracking
	--docdir=/usr/share/doc/flex"

build = "make"
pkg_create = "make DESTDIR=<pkg_dir> install &&
	ln -sv flex <pkg_dir>/usr/bin/lex"
