[ src ]

# snapshots can be found at:
# https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git

url = https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/snapshot/linux-firmware-<ver>.tar.gz
src_type = tar
src_dirname = linux-firmware-<ver>



[ vars ]



[ std ]

env =
prepare = tar --no-same-owner -xf <src_path> -C <tmp_dir>
configure =
build =
pkg_create = make FIRMWAREDIR=/usr/lib/firmware DESTDIR=<pkg_dir> install
