[ src ]

url = https://gitlab.freedesktop.org/xdg/shared-mime-info/-/archive/<ver>/shared-mime-info-<ver>.tar.gz
src_type = tar
src_dirname = <prog>-<ver>



[ vars ]



[ std ]

env =
prepare = tar --no-same-owner -xf <src_path> -C <tmp_dir>
configure = meson --prefix=/usr --libdir=lib --buildtype=release build
build = ninja -C build all
pkg_create = DESTDIR=<pkg_dir> ninja -C build install &&
	<pkg_dir>/usr/bin/update-mime-database <pkg_dir>/usr/share/mime
