[ src ]

url = https://download.gnome.org/sources/glib-networking/<ver_short>/glib-networking-<ver>.tar.xz
src_type = tar
src_dirname = <prog>-<ver>



[ vars ]



[ std ]

env =
prepare = tar --no-same-owner -xf <src_path> -C <tmp_dir>
configure = meson --prefix=/usr --libdir=lib --buildtype=release build
build = ninja -C build all
pkg_create = DESTDIR=<pkg_dir> ninja -C build install
