[ src ]

url = "https://mednafen.github.io/releases/files/mednafen-<ver>.tar.xz"
src_type = "tar"
src_dirname = "<prog>"



[ std ]

env = []
prepare = "tar --no-same-owner -xf <src_path> -C <tmp_dir>"
configure = "./configure
	--prefix=/usr
	--disable-nls
	--disable-dependency-tracking
	--disable-sdltest
	--disable-alsatest
	--disable-jack"

build = "make"
pkg_create = "make DESTDIR=<pkg_dir> install"
