[ src ]

url = "https://github.com/ThomasHabets/arping/archive/refs/tags/arping-<ver>.tar.gz"
src_type = "tar"
src_dirname = "<prog>-<prog>-<ver>"



[ std ]

env = []
prepare = "tar --no-same-owner -xf <src_path> -C <tmp_dir>"
configure = "./bootstrap.sh && ./configure
	--prefix=/usr
	--disable-dependency-tracking
	--enable-hardened"

build = "make"
pkg_create = "make DESTDIR=<pkg_dir> install"
