[ src ]

url = https://cpan.metacpan.org/authors/id/C/CH/CHORNY/Switch-<ver>.tar.gz
src_type = tar
src_dirname = <prog>-<ver>



[ vars ]



[ std ]

env =
prepare = tar --no-same-owner -xf <src_path> -C <tmp_dir>
configure =
build = PERL_MM_USE_DEFAULT=1 perl 'Makefile.PL' INSTALLDIRS='vendor'
pkg_create = make DESTDIR=<pkg_dir> install && chmod -Rv u+w <pkg_dir>/
