[ src ]

url = "https://w1.fi/releases/wpa_supplicant-<ver>.tar.gz"
src_type = "tar"
src_dirname = "<prog>-<ver>"



[ std ]

env = []
prepare = "tar --no-same-owner -xf <src_path> -C <tmp_dir>"
configure = "cp <prog_dir>/files/defconfig wpa_supplicant/.config"
build = "cd wpa_supplicant && make"
pkg_create = "mkdir -p <pkg_dir>/usr/bin <pkg_dir>/usr/share/man/man{5,8} &&
	cd wpa_supplicant &&
	cp wpa_cli wpa_supplicant <pkg_dir>/usr/bin/ &&
	cp doc/docbook/*.8 <pkg_dir>/usr/share/man/man8/ &&
	cp doc/docbook/*.5 <pkg_dir>/usr/share/man/man5/"

