[ src ]

url = "https://www.musl-libc.org/releases/musl-<ver>.tar.gz"
src_type = "tar"
src_dirname = "<prog>-<ver>"



[ std ]

env = []
prepare = "tar --no-same-owner -xf <src_path> -C <tmp_dir>"
configure = "./configure
	--prefix=
	--enable-wrapper=all
	--disable-shared"

build = "make"
pkg_create = "make DESTDIR=<pkg_dir> install"
