[ src ]

url = "https://github.com/vim/vim/archive/refs/tags/v<ver>.tar.gz
http://ftp.vim.org/vim/runtime/spell/pl.utf-8.spl
http://ftp.vim.org/vim/runtime/spell/en.utf-8.spl"

src_type = "tar"
src_dirname = "<prog>-<ver>"



[ std ]

env = []
prepare = "tar --no-same-owner -xf <src_path> -C <tmp_dir>"

# sed commands define the place for the global vimrc file as /etc/vimrc
configure = "./configure
	--prefix=/usr
	--sysconfdir=/etc
	--localstatedir=/var/lib/vim
	--enable-terminal
	--enable-cscope
	--disable-selinux
	--disable-xsmp
	--disable-xsmp-interact
	--disable-netbeans
	--disable-channel
	--disable-rightleft
	--disable-arabic
	--disable-gtktest
	--disable-icon-cache-update
	--disable-desktop-database-update
	--disable-canberra
	--disable-acl
	--disable-gpm
	--disable-sysmouse
	--disable-nls
	--disable-gui
	--without-x
	--without-local-dir
	--with-features=huge &&
	sed -E -i
		-e 's|^.*(#define SYS_.*VIMRC_FILE.*\").*$|\\1|g'
		-e 's|^.*(#define VIMRC_FILE.*\").*$|\\1|g'
		src/feature.h"

build = "make"
pkg_create = "make DESTDIR=<pkg_dir> install &&
	mkdir -p <pkg_dir>/{etc,usr/share/vim/vim<ver_pkgspec>/spell} &&
	mkdir -p <pkg_dir>/usr/share/vim/vim82/colors &&
	cp -a <src_dir>/*spl <pkg_dir>/usr/share/vim/vim<ver_pkgspec>/spell &&
	cp -a <prog_dir>/files/vimrc <pkg_dir>/etc/ &&
	cp -a <prog_dir>/files/*.vim <pkg_dir>/usr/share/vim/vim82/colors &&
	sed -i 's|__vim_shortver__|<ver_pkgspec>|g' <pkg_dir>/etc/vimrc &&
	rm -r <pkg_dir>/usr/share/{applications,icons}/"

