[ src ]

url = https://download.osgeo.org/libtiff/tiff-<ver>.tar.gz
src_type = tar
src_dirname = <prog>-<ver>



[ vars ]



[ std ]

env =
prepare = tar --no-same-owner -xf <src_path> -C <tmp_dir>
configure = ./configure
	--prefix=/usr
	--sysconfdir=/etc
	--mandir=/usr/share/man
	--with-docdir=/usr/share/doc/tiff
	--disable-static
	--disable-dependency-tracking

build = make
pkg_create = make DESTDIR=<pkg_dir> install &&
	rm -r <pkg_dir>/usr/share/{doc,man/man3}/
