[ src ]

url = "https://github.com/rhboot/efivar/releases/download/<ver>/efivar-<ver>.tar.bz2"
src_type = "tar"
src_dirname = "<prog>-<ver>"



[ std ]

env = [ "CFLAGS+=-D_GNU_SOURCE -Wno-error=address-of-packed-member" ]
prepare = "tar --no-same-owner -xf <src_path> -C <tmp_dir>"
configure = "git apply <prog_dir>/patch/<ver>-*.patch"
build = "ERRORS='' libdir=/usr/lib make"
pkg_create = "libdir=/usr/lib make DESTDIR=<pkg_dir> install"
