[ src ]

url = "https://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
https://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
https://dl-cdn.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz"

src_type = "alpine"
src_dirname = "rootfs"



[ std ]

env = [ "ADD_PROGS=loksh xorg-server xorg-server-common xorg-server-dev
xorgproto xorgxrdp xorgxrdp-dev setxkbmap xrandr libinput xf86-input-libinput xf86-video-modesetting alsa-utils alsa-utils-doc alsa-lib alsaconf alsa-ucm-conf mesa-dri-swrast kbd vim sed attr grep binutils findutils readline lsof less curl wget terminus-font ttf-inconsolata ttf-dejavu font-noto ttf-font-awesome font-noto-extra ttf-liberation git make gcc g++ libx11-dev libxft-dev libxinerama-dev ncurses dbus-x11 firefox adwaita-icon-theme chromium desktop-file-utils" ]

prepare = "apk update"
configure = ""
build = "apk add --no-chown <prog> ${ADD_PROGS}"

# fontconfig, firefox, chromium, gcc and certs need to have links to be relative
# broken links in /etc/fonts/conf.d are removed
pkg_create = "cp -av <build_dir>/rootfs/* <pkg_dir>/ &&
	for f in <pkg_dir>/etc/fonts/conf.d/*.conf; do
		fbase=\"$(basename \"${f}\")\";
		ln -sf \"../../../usr/share/fontconfig/conf.avail/${fbase}\"
			\"<pkg_dir>/etc/fonts/conf.d/${fbase}\";
	done &&
	for f in <pkg_dir>/etc/ssl/certs/*.pem; do
		flink=\"$(readlink \"${f}\")\";
		ln -vsf \"../../..//${flink}\" \"${f}\";
	done &&
	rm <pkg_dir>/etc/fonts/conf.d/{30-liberation-mono.conf,30-liberation-sans-narrow.conf,30-liberation-sans.conf,30-liberation-serif.conf,45-dejavu.conf,45-liberation.conf,45-liberation-sans-narrow.conf,75-yes-terminus.conf,90-liberation-sans-narrow.conf,90-liberation.conf,90-tt-dejavu.conf} &&
	ln -sf ../../usr/lib/firefox/firefox <pkg_dir>/usr/bin/firefox &&
	ln -sf ../../usr/lib/chromium/chromium-launcher.sh
		<pkg_dir>/usr/bin/chromium-browser &&
	ln -sf ../../..//usr/libexec/gcc/x86_64-alpine-linux-musl/11.2.1/liblto_plugin.so
		<pkg_dir>/usr/lib/bfd-plugins/liblto_plugin.so &&
	cd <pkg_dir> && chmod 755 proc && rm -rf {media,opt,srv,var/*}"
