[ src ]

url = https://github.com/llvm/llvm-project/releases/download/llvmorg-<ver>/llvm-<ver>.src.tar.xz
src_type = tar
src_dirname = <prog>-<ver>.src



[ vars ]



[ std ]

env =
prepare = tar --no-same-owner -xf <src_path> -C <tmp_dir>
configure = mkdir build && cd build && cmake
	-D CMAKE_INSTALL_PREFIX=/usr
	-D CMAKE_INSTALL_LIBDIR=/usr/lib
	-D CMAKE_BUILD_TYPE='Release'
	-D LLVM_BUILD_DOCS=OFF
	-D LLVM_BUILD_LLVM_DYLIB=ON
	-D LLVM_BUILD_TESTS=OFF
	-D LLVM_ENABLE_BINDINGS=OFF
	-D LLVM_ENABLE_FFI=ON
	-D LLVM_ENABLE_RTTI=ON
	-D LLVM_ENABLE_SPHINX=OFF
	-D LLVM_INCLUDE_BENCHMARKS=OFF
	-D LLVM_INSTALL_UTILS=ON
	-D LLVM_LINK_LLVM_DYLIB=ON
	..

build = cd build && make
pkg_create = cd build && make DESTDIR=<pkg_dir> install
