[ src ]

url = "https://www.cpan.org/authors/id/B/BJ/BJOERN/<prog>-<ver>.tar.gz"
src_type = "tar"
src_dirname = "<prog>-<ver>"



[ std ]

env = []
prepare = "tar --no-same-owner -xf <src_path> -C <tmp_dir>"
configure = ""
build = "PERL_MM_USE_DEFAULT=1 perl 'Makefile.PL' INSTALLDIRS='vendor'"
pkg_create = "make pure_install doc_install DESTDIR=<pkg_dir>"
