[ src ]

url = "https://poppler.freedesktop.org/poppler-<ver>.tar.xz"
src_type = "tar"
src_dirname = "<prog>-<ver>"



[ std ]

env = []
prepare = "tar --no-same-owner -xf <src_path> -C <tmp_dir>"

configure = "mkdir build && cd build && cmake
	-D CMAKE_INSTALL_PREFIX=/usr
	-D CMAKE_INSTALL_LIBDIR=/usr/lib
	-D OpenJPEG_DIR=/usr/lib
	-D OpenJPEG_INCLUDE_DIR=/usr/include
	-D CMAKE_BUILD_TYPE='Release'
	-D WITH_GTK=ON
	-D WITH_Iconv=ON
	-D ENABLE_CPP=ON
	-D ENABLE_BOOST=OFF
	-D BUILD_CPP_TESTS=OFF
	-D BUILD_GTK_TESTS=OFF
	-D BUILD_MANUAL_TESTS=OFF
	-D BUILD_QT5_TESTS=OFF
	-D BUILD_QT6_TESTS=OFF
	-D ENABLE_LIBCURL=OFF
	-D ENABLE_QT5=OFF
	-D ENABLE_QT6=OFF
	-D WITH_Cairo=OFF
	-D WITH_GObjectIntrospection=OFF
	-D WITH_NSS3=OFF
	.."

build = "cd build && make"
pkg_create = "cd build && make DESTDIR=<pkg_dir> install"
