[ src ]

url = "http://download.joedog.org/siege/siege-<ver>.tar.gz"
src_type = "tar"
src_dirname = "<prog>-<ver>"



[ std ]

env = []
prepare = "tar --no-same-owner -xf <src_path> -C <tmp_dir>"
configure = "./configure
	--prefix=/usr
	--sysconfdir=/etc
	--mandir=/usr/share/man
	--disable-dependency-tracking
	--disable-static
	--disable-nls"

build = "make"
pkg_create = "make DESTDIR=<pkg_dir> install"
