[ src ]

url = "https://github.com/thom311/libnl/releases/download/libnl<ver_pkgspec>/libnl-<ver>.tar.gz"
src_type = "tar"
src_dirname = "<prog>-<ver>"



[ std ]

env = []
prepare = "tar --no-same-owner -xf <src_path> -C <tmp_dir>"
configure = "./configure
	--prefix=/usr
	--disable-static
	--disable-cli
	--disable-dependency-tracking"

build = "make"
pkg_create = "make DESTDIR=<pkg_dir> install &&
	mv <pkg_dir>/usr/etc/ <pkg_dir>/usr/share/"
