[ src ]

url = "http://ftp.rpm.org/popt/releases/popt-1.x/popt-<ver>.tar.gz"
src_type = "tar"
src_dirname = "<prog>-<ver>"



[ std ]

env = []
prepare = "tar --no-same-owner -xf <src_path> -C <tmp_dir>"
configure = "./autogen.sh && ./configure
	--prefix=/usr
	--disable-static
	--disable-dependency-tracking
	--disable-nls"

build = "make"
pkg_create = "make DESTDIR=<pkg_dir> install"
