[ src ]

url = https://github.com/pypa/setuptools/archive/v<ver>/<prog>-<ver>.tar.gz
src_type = tar
src_dirname = <prog>-<ver>



[ vars ]



[ std ]

env =
prepare = tar --no-same-owner -xf <src_path> -C <tmp_dir>
configure =
build = python setup.py build
pkg_create = mkdir build/scripts-3.9 &&
	python setup.py install
	--prefix=/usr
	--skip-build
	--root=<pkg_dir>
	--optimize=1 &&
	 find <pkg_dir> -depth -type f -name '*.py[co]' -delete
		 -o -type d -name __pycache__ -delete
